---
- name: Development Environment Setup
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    device_type_env: "{{ lookup('env', 'SYSTEM_DEVICE_TYPE') | default(Undefined, true) }}"

  # needed for beutiful output callback
  roles:
    - role: townk.beautiful_output

  pre_tasks:
    - pause:
        prompt: "Enter device type (one of: desktop, laptop)"
      register: prompt
      when: device_type_env is undefined

    - name: "Set 'device_type' fact"
      set_fact:
        device_type: "{{ device_type_env | default(prompt.user_input, true) | lower | trim }}"
      tags: always

    - name: Validate 'device_type'
      assert:
        that: device_type in ['desktop', 'laptop']
        fail_msg: "Invalid device type '{{ device_type }}', specify one of ['desktop', 'laptop']"
      tags: always

    - name: Detect gpu_vendor (via lspci)
      ansible.builtin.shell: lspci -nn | grep -i vga
      register: gpu_info
      changed_when: false   # detection shouldn't mark host as changed
      tags: always

    - name: Set 'gpu_vendor' fact
      set_fact:
        gpu_vendor: >-
          {%- if 'NVIDIA' in gpu_info.stdout -%}
          NVIDIA
          {%- elif 'AMD' in gpu_info.stdout or 'ATI' in gpu_info.stdout -%}
          AMD
          {%- elif 'Intel' in gpu_info.stdout -%}
          INTEL
          {%- else -%}
          UNKNOWN
          {%- endif -%}
      tags: always

    - name: "Print System Info"
      ansible.builtin.debug:
        msg: "DEVICE: {{ device_type }, }OS: {{ ansible_distribution }}, GPU: {{ gpu_vendor }}"

  tasks:
    - name: Run common roles
      ansible.builtin.include_role:
        name: "{{ item }}"
        apply:
          tags: "{{ item.split('_') }}"
      loop: "{{ common_roles }}"
      tags: always

    - name: Run desktop roles
      when: device_type == 'desktop'
      ansible.builtin.include_role:
        name: "{{ item }}"
        apply:
          tags: "{{ item.split('_') }}"
      loop: "{{ desktop_roles }}"
      tags: always

    - name: Run laptop roles
      when: device_type == 'laptop'
      ansible.builtin.include_role:
        name: "{{ item }}"
        apply:
          tags: "{{ item.split('_') }}"
      loop: "{{ laptop_roles }}"
      tags: always

