---
- name: Development Environment Setup
  hosts: localhost
  connection: local
  gather_facts: yes

  # needed for beutiful output callback
  roles:
    - role: townk.beautiful_output

  # You can prompt for device_type or pass it via CLI (-e)
  vars_prompt:
    - name: device_type
      prompt: "Enter device type (e.g., desktop, laptop)"
      private: false
      default: "desktop"

  pre_tasks:
    - name: Validate device type
      assert:
        that: device_type in ['desktop', 'laptop']
        fail_msg: "Invalid device type '{{ device_type }}', specify one of ['desktop', 'laptop']"
        success_msg: "Input looks good! Running for {{ device_type }}"
      tags: always

  tasks:
    - name: Run common roles
      ansible.builtin.include_role:
        name: "{{ item }}"
        apply:
          tags: "{{ item.split('_') }}"
      loop: "{{ common_roles }}"
      tags: always

    - name: Run desktop roles
      when: device_type == 'desktop'
      ansible.builtin.include_role:
        name: "{{ item }}"
        apply:
          tags: "{{ item.split('_') }}"
      loop: "{{ desktop_roles }}"
      tags: always

    - name: Run laptop roles
      when: device_type == 'laptop'
      ansible.builtin.include_role:
        name: "{{ item }}"
        apply:
          tags: "{{ item.split('_') }}"
      loop: "{{ laptop_roles }}"
      tags: always

