---
- name: "{{ ansible_facts['distribution'] }} | CLI STUFF | Install"
  community.general.pacman:
    name:
      - bat
      - btop
      - fd
      - ripgrep
      - ncdu
      - fastfetch
    state: present
  become: true