---
- name: "{{ ansible_distribution}} | wifi | Checking for distro config..."
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: distribution_config

- name: "{{ ansible_distribution}} | wifi | Running tasks..."
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: distribution_config.stat.exists