---
- name: "{{ ansible_facts['distribution'] }} | POST SETUP | Disabling annoying ass beeping sound"
  ansible.builtin.copy:
    dest: /etc/modprobe.d/nobeep.conf
    content: |
      # Disable PC speaker beep
      blacklist pcspkr
      blacklist snd_pcsp
    owner: root
    group: root
    mode: '0644'
  when: device_type == "laptop"
  become: true

- name: "{{ ansible_facts['distribution'] }} | POST SETUP | Enabling 'TearFree' option for AMD drivers"
  ansible.builtin.copy:
    dest: /etc/X11/xorg.conf.d/20-amdgpu.conf
    content: |
      Section "OutputClass"
          Identifier "AMD"
          Option "TearFree" "true"
      EndSection
    owner: root
    group: root
    mode: '0644'
  when: gpu_vendor == "AMD"
  become: true

- name: "{{ ansible_facts['distribution'] }} | POST SETUP | Coppying ly login manager config"
  ansible.builtin.copy:
    dest: /etc/ly/config.ini
    src: ly_config.ini
    owner: root
    group: root
    mode: '0644'
  become: true

- name: "{{ ansible_facts['distribution'] }} | POST SETUP | Editing faillock.conf to increase incorrect password attempts"
  ansible.builtin.lineinfile:
    path: /etc/security/faillock.conf
    regexp: '^(#\s*)?{{ current_rule.key }}\s*='
    line: "{{ current_rule.key }} = {{ current_rule.value }}"
    state: present
  loop:
    - { key: 'deny', value: '10' }
    - { key: 'unlock_time', value: '60' }
  loop_control:
      loop_var: current_rule
  become: true

- name: "{{ ansible_facts['distribution'] }} | POST SETUP | Configuring touchpad tapping + natural scroll"
  ansible.builtin.copy:
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf
    content: |
      Section "InputClass"
        Identifier "touchpad-config"
        Driver "libinput"
        Option "Tapping" "on"
        Option "NaturalScrolling" "true"
        Option "ClickMethod" "clickfinger"
      EndSection
    owner: root
    group: root
    mode: '0644'
  when: device_type == "laptop"
  become: true

- name: "{{ ansible_facts['distribution'] }} | POST SETUP | TLP enable wifi radio on boot"
  ansible.builtin.lineinfile:
    path: /etc/tlp.conf
    regexp: '#DEVICES_TO_ENABLE_ON_STARTUP='
    line: 'DEVICES_TO_ENABLE_ON_STARTUP="wifi"'
    state: present
  become: true

# - name: "{{ ansible_facts['distribution'] }} | Configuring Nix GPU driver passthrough"
#   ansible.builtin.copy:
#     dest: /etc/tmpfiles.d/nix-opengl.conf
#     content: |
#       # Type  Path                 Mode UID GID Age Argument
#       L+      /run/opengl-driver   -    -   -   -   /nix/var/nix/profiles/nix-gpu-64bit
#       L+      /run/opengl-driver-32 -   -   -   -   /nix/var/nix/profiles/nix-gpu-32bit
#     mode: '0644'
#     owner: root
#     group: root
#   when: gpu_vendor == "AMD"
#   become: true